### ISSUE TITLE
Server Issues ?

### ISSUE THREAD

**Issue by dave-1234** [ghost1372/Easegram#8]
Hey Mahdi !
I tested the latest version yesterday, it worked fine but then suddenly not anymore. There are no more likes coming in although the app appears to work/load when I click start. Server issues again?
Any idea what could be done to reduce the server issues?

Thank you for your help! Great App !!
David

**Comment by ghost1372** [comment]
hi @dave-1234  The server I used in the program is for the Russians, so we dont have any access to control that, We recently received reports from many users about this issue And it can only be one of the following:
1.Instagram provides robot detection (Do not like too much for one post because you must wait at least 24h for another post like but you can use on another users posts)
2.The Russian server is blocking a lot of activity on a post
test on another account you can see app works fine.
Thank you for your favor.
